rmap-project/rmap

api/src/main/java/info/rmapproject/api/responsemgr/StatementResponseManager.java, api/src/test/java/info/rmapproject/api/responsemgr/StatementResponseManagerTest.java, core/src/main/java/info/rmapproject/core/rmapservice/impl/openrdf/ORMapService.java
Fix for issue #2.  Applied fix to both /discos and /agents. Now returns 404 error if statement doesn't exist.
=> /stmts/{s}/{p}/{o}/discos now returns 404 when no match

webapp/src/main/java/info/rmapproject/webapp/controllers/DataDisplayController.java, webapp/src/main/java/info/rmapproject/webapp/controllers/SearchController.java, webapp/src/main/webapp/WEB-INF/views/search.jsp, webapp/src/main/webapp/WEB-INF/web.xml
Fixes https://github.com/rmap-project/rmap/issues/6
Previously, a search on an invalid URI would fail with a generic error.  The user is now redirected back to the search form with a notice saying that an invalid URI was provided. Removed some unnecessary decode commands. Also made the example URIs into links so they stand out.
=> Handle invalid URIs in search form

.gitignore, api/pom.xml, api/src/test/java/info/rmapproject/api/utils/HttpHeaderDateUtilsTest.java, auth/pom.xml, core/pom.xml, pom.xml, testdata/pom.xml, webapp/pom.xml
- Collapse properties to the parent pom
- Use property placeholders for versions of dependencies
- Move dependency boilerplate to parent pom (plugin and dependency management)
- Add .gitignore
=> Maven parent pom (#35)

webapp/src/main/java/info/rmapproject/webapp/domain/ResourceDescription.java, webapp/src/main/java/info/rmapproject/webapp/service/DataDisplayServiceImpl.java
Null exception thrown when no types available for a resource. Changed to ignore nulls.
Fixed #82 - Graph visuals were displaying literal values as nodes.
=> Fixed two small GUI bugs including #82

core/src/main/java/info/rmapproject/core/rdfhandler/RDFType.java, core/src/main/java/info/rmapproject/core/rdfhandler/impl/openrdf/RioRDFHandler.java
Support N-Quad parsing by adding the RMap `RDFType.NQUADS` and mapping it to the OpenRDF model type `RDFFormat.NQUADS`.
Closes #92.
=> Support N-Quad parsing.

core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapAgent.java
Removes un-used field, and avoids a ClassCastException when the graph identifier (i.e. officialAgentId) is null.
Closes #90.
=> Avoid a ClassCastException when the officialAgentId is null.

core/src/main/java/info/rmapproject/core/rdfhandler/impl/openrdf/RioRDFHandler.java
When using RioRDFHandler to convert event2Rdf, part of the method identifies the event type.  Some events types were not listed, causing an error stating the event type was not recognized.  Added missing event types
=> Bug fix - retrieving certain events resulted in unrecognized event type error

core/src/main/java/info/rmapproject/core/model/RMapBlankNode.java, core/src/main/java/info/rmapproject/core/model/RMapResource.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapAgent.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapDiSCO.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEvent.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventDeletion.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventDerivation.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventInactivation.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventTombstone.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventUpdate.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventUpdateWithReplace.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventWithNewObjects.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapObject.java, core/src/main/java/info/rmapproject/core/model/request/RMapRequestAgent.java, core/src/main/java/info/rmapproject/core/rmapservice/impl/openrdf/ORMapObjectMgr.java, core/src/test/java/info/rmapproject/core/ObjectSerializationTest.java, core/src/test/java/info/rmapproject/core/SerializationAssertions.java, core/src/test/java/info/rmapproject/core/TestUtil.java, integration/pom.xml, integration/src/main/resources/integration-triplestore.xml, integration/src/test/java/info/rmapproject/integration/ManagerObjectSerializationIT.java, pom.xml
- add hashCode() and equals(Object) to support unit tests; these methods are value-based: instances are compared on a field-by-field basis.  The equals implementation used will break the contract of the equals method due to subclassing, but that is an acceptable compromise. 
- add toString() methods where they were not implemented previously, to support comparison during unit testing 
- add 'serialVersionUID' and `implements java.io.Serializable` to the domain objects 
- include unit and integration tests which provide smoke tests of round tripping (object -> bytes -> object) domain object graphs. 
- share test utility classes from the core module to integration module
=> Update the RMap domain objects to support java.io.Serializable

core/src/main/java/info/rmapproject/core/model/RMapBlankNode.java, core/src/main/java/info/rmapproject/core/model/RMapIri.java, core/src/main/java/info/rmapproject/core/model/RMapResource.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapAgent.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapDiSCO.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEvent.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventCreation.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventDeletion.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventDerivation.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventInactivation.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventTombstone.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventUpdate.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventUpdateWithReplace.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventWithNewObjects.java
Insure each class in the RMap domain hierarchy immediately declares (i.e. not via inheritance) a "serialVersionUID" for java.io.Serializable.
=> Add missing serialVersionUID field to RMap domain objects

api/src/main/java/info/rmapproject/api/auth/ApiUserServiceImpl.java, api/src/main/java/info/rmapproject/api/responsemgr/AgentResponseManager.java, api/src/main/java/info/rmapproject/api/responsemgr/DiscoResponseManager.java, api/src/main/java/info/rmapproject/api/responsemgr/EventResponseManager.java, api/src/main/java/info/rmapproject/api/responsemgr/ResourceResponseManager.java, api/src/main/java/info/rmapproject/api/responsemgr/StatementResponseManager.java, auth/src/main/java/info/rmapproject/auth/service/UserRMapAgentServiceImpl.java, core/src/main/java/info/rmapproject/core/rmapservice/RMapService.java, core/src/main/java/info/rmapproject/core/rmapservice/impl/openrdf/ORMapObjectMgr.java, core/src/main/java/info/rmapproject/core/rmapservice/impl/openrdf/ORMapService.java, core/src/test/java/info/rmapproject/core/rmapservice/impl/openrdf/ORMapAgentMgrTest.java, core/src/test/java/info/rmapproject/core/rmapservice/impl/openrdf/ORMapResourceMgrTest.java, webapp/src/main/java/info/rmapproject/webapp/controllers/ResourceDisplayController.java, webapp/src/main/java/info/rmapproject/webapp/service/DataDisplayServiceImpl.java
- Connection was hanging due to apparent quirk with retrieving statements that contain a Resource that doesn't exist in the database.  This leaves the connection open and uses up the concurrent connections
allowed.  This was specifically a problem when checking for an RMap type using ORMapObjectMgr.isRMapType().  Now checks the context exists before checking the type statement.
- Some logging added to help resolve the issue
- Added code to webapp to ensure all connections close even when code errors
- Change ORMapService to use only Autowired constructor
=> Resolve connection hang in webapp

core/src/main/java/info/rmapproject/core/rmapservice/impl/openrdf/triplestore/SesameTriplestore.java, integration/src/test/java/info/rmapproject/integration/TriplestoreIT.java
The backstory is that I was developing an IT for the indexing-related code, and needed access to the triplestore `RepositoryConnection` to read in an `InputStream` of statements.  The `SesameTriplestore` instance gave me a `RepositoryConnection` but it was closed, which made no sense.  That is, I don't know why the connection would be closed upon request:
```java
rmapObjects.values().stream().flatMap(Set::stream).forEach(source -> {
try (InputStream in = source.getInputStream();
RepositoryConnection c = triplestore.getConnection();) {
assertTrue(c.isOpen());
c.add(in, "http://foo/bar", source.getRdfFormat());
} ...
```
The `assertTrue` was failing in the above codeblock without the fix supplied in this PR.
The way `SesameTriplestore` manages connections is not something I have time to …
=> Update the SesameTriplestore to actually consult the underlying RepositoryConnection object to determine its status as "open" or "closed".

core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapDiSCO.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/OStatementsAdapter.java, core/src/test/java/info/rmapproject/core/model/impl/openrdf/ORMapDiscoTest.java, core/src/test/java/info/rmapproject/core/rmapservice/impl/openrdf/OStatementsAdapterTest.java, testdata/src/main/java/info/rmapproject/testdata/service/TestFile.java, testdata/src/main/resources/discos/discoA_nonaggregateroots.ttl
- Closes issue #85.  See issue for full details of change
- Moved logic for checking connected resources to OStatementsAdapter - the only place it is used.   Removed it from ORMapDiSCO.
- Added a few tests for OStatementAdapter. The ones for asDisco just check for exceptions, left a todo to add content checks for these
=> Removed constraint on stmts being rooted to Aggregated resources

core/src/main/java/info/rmapproject/core/model/RMapLiteral.java, core/src/main/java/info/rmapproject/core/model/event/RMapEvent.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEvent.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventCreation.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventDeletion.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventDerivation.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventInactivation.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventTombstone.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventUpdate.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventUpdateWithReplace.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapEventWithNewObjects.java, core/src/main/java/info/rmapproject/core/model/impl/openrdf/OStatementsAdapter.java, core/src/main/java/info/rmapproject/core/rmapservice/impl/openrdf/ORMapEventMgr.java, core/src/main/java/info/rmapproject/core/utils/Terms.java, core/src/main/java/info/rmapproject/core/vocabulary/impl/openrdf/RMAP.java, core/src/test/java/info/rmapproject/core/model/impl/openrdf/ORMapCommonEventTest.java, core/src/test/java/info/rmapproject/core/model/impl/openrdf/ORMapEventCreationTest.java, core/src/test/java/info/rmapproject/core/model/impl/openrdf/ORMapEventDeletionTest.java, core/src/test/java/info/rmapproject/core/model/impl/openrdf/ORMapEventDerivationTest.java, core/src/test/java/info/rmapproject/core/model/impl/openrdf/ORMapEventInactivationTest.java
* Adds `RMapEvent#{set, get}LineageProgenitor(RMapIri)` for exposure of lineage in Java API
* Adds ORMap implementation of lineage progenitor via `rmap:progenitor` property`
* Tests that the (possibly null) lineage progenitor value survives round-trips to the triplestore.
Interested Parties:  @emetsger, @karenhanson
Resolves #142
=> Add lineage progenitor to core model

core/src/main/java/info/rmapproject/core/rmapservice/RMapService.java, core/src/main/java/info/rmapproject/core/rmapservice/impl/openrdf/ORMapDiSCOMgr.java, core/src/main/java/info/rmapproject/core/rmapservice/impl/openrdf/ORMapQueriesLineage.java, core/src/main/java/info/rmapproject/core/rmapservice/impl/openrdf/ORMapService.java, core/src/main/java/info/rmapproject/core/utils/Terms.java, core/src/test/java/info/rmapproject/core/CoreTestAbstract.java, core/src/test/java/info/rmapproject/core/rmapservice/impl/openrdf/ORMapDiSCOMgrTest.java, core/src/test/java/info/rmapproject/core/rmapservice/impl/openrdf/ORMapQueriesLineageTest.java
* Exposes Java API for finding the lineage progenitor of DiSCOs via `RMapService#getLineageProgenitor(URI discoURI)`
* Places `rmap:lineageProgenitor` property in DiSCO-related CRUD events
Interested parties: @emetsger @karenhanson 
Resolves #148
=> Populate and expose lineage progenitor

core/pom.xml, core/src/test/java/info/rmapproject/core/idservice/HttpUrlIdServiceTest.java, pom.xml
Remove use of powermock, which is incompatible with mockito 2.11.  Ignore two tests that use powermock in HttpUrlIdServiceTest.
This is PR 2 of ?, ultimately resulting in the merging of the indexing work.
=> Upgrade to mockito 2.11.0 from 1.10.19.

api/src/main/java/info/rmapproject/api/responsemgr/DiscoResponseManager.java, api/src/test/java/info/rmapproject/api/responsemgr/DiscoResponseManagerTest.java, core/src/main/java/info/rmapproject/core/rmapservice/RMapService.java, core/src/main/java/info/rmapproject/core/rmapservice/impl/openrdf/ORMapDiSCOMgr.java, core/src/main/java/info/rmapproject/core/rmapservice/impl/openrdf/ORMapQueriesLineage.java, core/src/main/java/info/rmapproject/core/rmapservice/impl/openrdf/ORMapService.java, core/src/test/java/info/rmapproject/core/rmapservice/impl/openrdf/ORMapDiSCOMgrTest.java, core/src/test/java/info/rmapproject/core/rmapservice/impl/openrdf/ORMapQueriesLineageTest.java, webapp/src/main/java/info/rmapproject/webapp/service/DataDisplayServiceImpl.java
* Clarifies and renames methods for finding versions and derivatives of discos in `RMapService`
* Uses event lineage sparql queries for finding versions and derives, rather than event crawling
Resolves #143
=> Use lineage internally for finding versions

auth/src/main/java/info/rmapproject/auth/model/ApiKey.java, auth/src/main/java/info/rmapproject/auth/model/User.java, auth/src/main/java/info/rmapproject/auth/model/UserIdentityProvider.java, webapp/src/main/java/info/rmapproject/webapp/controllers/ApiKeyController.java, webapp/src/main/java/info/rmapproject/webapp/controllers/SitePropertiesToModelInterceptor.java, webapp/src/test/java/info/rmapproject/webapp/controllers/ApiKeyControllerTest.java
Investigated this after noticing that when using in-memory derby, an error occurs on the key download page saying can't lazy load the data. It does not occur on live tests.  To resolve this, made the following changes:
- Force lazy=false on the database model. My best guess at what is happening is that different connections configurations have different default behavior wrt ending session on commit. In particular, it seems the in-memory derbydb ends the session on commit which causes anything that has lazy load not to load when retrieved after commit e.g. ApiKey.getUserId(). This happens in the ApiKeyController.downloadKey() method.  We can either disable session close on commit for each
connection, or just force lazy=false by adding an annotation to the data model classes - this makes it …
=> Add lazy=false to db model objects

indexing-solr/src/main/java/info/rmapproject/indexing/kafka/DefaultIndexRetryHandler.java, indexing-solr/src/main/java/info/rmapproject/indexing/kafka/IndexingConsumer.java, indexing-solr/src/main/resources/rmap-indexing-solr.xml
Use prototype scope for `DefaultIndexRetryHandler` since one of its member variables, `ORMapService`, cannot be shared by multiple threads.
- Contributes to the fix for #175
=> Use prototype scope for `DefaultIndexRetryHandler`

api/src/main/java/info/rmapproject/api/responsemgr/AgentResponseManager.java, api/src/main/java/info/rmapproject/api/responsemgr/DiscoResponseManager.java, api/src/main/java/info/rmapproject/api/responsemgr/EventResponseManager.java, api/src/main/java/info/rmapproject/api/responsemgr/ResourceResponseManager.java, api/src/main/java/info/rmapproject/api/responsemgr/StatementResponseManager.java, api/src/main/java/info/rmapproject/api/service/AgentApiService.java, api/src/main/java/info/rmapproject/api/service/DiSCOApiService.java, api/src/main/java/info/rmapproject/api/service/EventApiService.java, api/src/main/java/info/rmapproject/api/service/ResourceApiService.java, api/src/main/java/info/rmapproject/api/service/RootApiService.java, api/src/main/webapp/WEB-INF/beans.xml, api/src/test/java/info/rmapproject/api/service/RootApiServiceTest.java
Closes issue #4
Also:
- Corrected the paths in the comments of the API Service classes 
- Added missing `GET /agents` message
- Replaced description json with URL to documentation.
=> Add default message for RMap API root path

indexing-solr/src/main/java/info/rmapproject/indexing/kafka/DefaultIndexRetryHandler.java, indexing-solr/src/main/java/info/rmapproject/indexing/solr/repository/DiscosSolrOperations.java, integration/src/test/java/info/rmapproject/integration/BaseHttpIT.java, integration/src/test/java/info/rmapproject/integration/SmokeTestIT.java, integration/src/test/java/info/rmapproject/integration/TombstoneAndHardDeleteIT.java
* Indexer now removes documents in the index that pertain _only_ to the tombstoned DiSCO (the indexer used to remove the entire lineage)
* Includes an IT based on the information in #176.
=> Properly handle tombstones when indexing

indexing-solr/src/main/java/info/rmapproject/indexing/solr/repository/DiscoRepository.java, indexing-solr/src/test/java/info/rmapproject/indexing/solr/repository/DiscoRepositoryTest.java
- Added two new queries. One retrieves search results list for search page including highlighted terms and facets for filtering, the other searches only on additional statements and is used to retrieve node labels.
- Added tests for new queries
=> Added Solr search queries for RMap GUI search results

indexing-solr/src/main/java/info/rmapproject/indexing/kafka/LineagePartitioner.java, indexing-solr/src/test/java/info/rmapproject/indexing/kafka/LineagePartitionerTest.java, indexing-solr/src/test/resources/event-producer.properties, integration/src/main/resources/event-producer.properties
This implements a Kafka Partitioner that insures events pertaining to a lineage go to the same Kafka partition.  Events that do not have a progenitor lineage URI are simply assigned based on the hash code of the event object.
Note that this implementation is sensitive to the number of Kafka partitions that are configured for the RMap event topic.  If the number of partitions changes, then the algorithm implemented in this commit will end up assigning events that once went to PartitionA to go to PartitionB.  This will break the guarantee that events pertaining to a lineage are contained within a single partition.  Care should be taken if the number of partitions for the RMap event topic are ever increased in the future.
Includes unit test.
This closes #144 and #138.
=> Assign RMap events to Kafka partitions based on progenitor lineage URI

api/src/main/webapp/WEB-INF/web.xml, webapp/src/main/webapp/WEB-INF/web.xml
Avoids the need to override the settings using catalina.properites.
=> Change default profiles to match production defaults

webapp/src/main/java/info/rmapproject/webapp/controllers/AccountController.java, webapp/src/main/java/info/rmapproject/webapp/controllers/ResourceDisplayController.java, webapp/src/main/java/info/rmapproject/webapp/service/DataDisplayServiceImpl.java, webapp/src/main/java/info/rmapproject/webapp/utils/WebappUtils.java, webapp/src/main/webapp/includes/js/pagecontrol.js, webapp/src/main/webapp/includes/js/searchcontrol.js, webapp/src/test/java/info/rmapproject/webapp/utils/WebappUtilsTest.java
A handful of minor GUI fixes
- Snippets were not displaying highlighted text where first highlight was too far into the string.
- If you did a second search while on page 2 of search results, the page number did not reset.
- Agent graph had authId set as type "other" instead of "no type"
- Added missing close node info popup command to pagecontrol.js
- Ensure session use information is refreshed after setting update
- Removed unused import
=> Fix snippet length and other minor issues

api/src/main/resources/logback.xml, webapp/src/main/resources/logback.xml
logback.xml is needed to set log levels on live apps, previously it was only available in integration. Copied it to the relevant modules.
=> Copy logback.xml from integration to webapp and api modules

webapp/src/main/java/info/rmapproject/webapp/controllers/ResourceDisplayController.java, webapp/src/main/java/info/rmapproject/webapp/service/DataDisplayServiceImpl.java, webapp/src/main/resources/typemappings.properties, webapp/src/main/webapp/includes/stylesheets/layout.css
Three small GUI fixes and added a few type mappings:
1) in the DiSCO graph, the types weren't being calculated correctly for the subject resource of a triple, fixed this.
2) when the Resource label included embedded HTML, the label would be displayed incorrectly. Added code to strip HTML from the Resource label
3) made text box width flexible - fixed with was messing with responsive layout
4) Added 2 more type mappings for IEEE DiSCOs - FundingAgency and Journal
=> Fixed resource label and DiSCO types

auth/src/main/resources/spring-rmapauth-context.xml, integration/src/main/resources/integration-db.xml
The bean definition deliberately excludes the (unused) databaseCleaner property.
The bean definition parser for `jdbc:initialize-database` will set the `databaseCleaner` property of `DataSourceInitializer` even when no `DESTROY` scripts have been set.  The (impotent) cleaner will be executed when `destroy()` is called, leading to the connection exception (because Postgres is no longer available).
Closes #213.
=> Replace jdbc:initialize-database with a standard bean definition

integration/pom.xml
Increases timeout for Tomcat container. This fixes an intermittent error that happens when building integration module:
`
[ERROR] Failed to execute goal org.codehaus.cargo:cargo-maven2-plugin:1.6.3:start (start-container) on project rmap-integration: Cannot start container [org.codehaus.cargo.container.tomcat.Tomcat8xInstalledLocalContainer@12cfc095]:
Deployable [http://localhost:61237/cargocpc/index.html] failed to finish deploying within the timeout period [120000]. The Deployable state is thus unknown.
`
=> Increase Tomcat container timeout

integration/src/main/resources/rmap.properties, kafka-shared/src/main/resources/event-consumer.properties, kafka-shared/src/main/resources/event-producer.properties, kafka-shared/src/main/resources/rmap-kafka-shared.xml
Also corrects the value of `bootstrap.servers` property for integration tests.
=> Update Kafka producer and consumer configurations to read properties from the primary RMap configuration file

api/pom.xml, pom.xml, webapp/pom.xml
Avoids a bug where test resources were getting packaged in deployed wars.
=> Use version 3.2.0 of the maven-war-plugin.

pom.xml
This PR allows an individual to deploy snapshot artifacts to the Data Conservancy Maven repository using `mvn deploy`.  If you are off-campus, one needs to activate the `external` profile included in this PR using `mvn deploy -Dexternal`.
In order to deploy _at all_, one needs to have SSH public key authentication set up between the computer/user running `mvn deploy` and the Maven server.
=> Support deployment of snapshot artifacts to the DC Maven repository.

core/src/main/java/info/rmapproject/core/idservice/HttpArkIdService.java
This is a quick fix to resolve filelock issue found during stress tests on server.  This may have negative consequences for performance and need further review at a later date.
=> Convert HttpArkIdService.createId() to synchronized

api/src/main/java/info/rmapproject/api/utils/PathUtils.java, api/src/test/java/info/rmapproject/api/responsemgr/AgentResponseManagerTestIT.java, api/src/test/java/info/rmapproject/api/responsemgr/DiscoResponseManagerTestIT.java, api/src/test/java/info/rmapproject/api/responsemgr/EventResponseManagerTestIT.java, api/src/test/java/info/rmapproject/api/responsemgr/ResourceResponseManagerTestIT.java, api/src/test/java/info/rmapproject/api/service/ResourceApiServiceTestIT.java, webapp/src/main/java/info/rmapproject/webapp/controllers/AgentDisplayController.java, webapp/src/main/java/info/rmapproject/webapp/controllers/DiSCODataController.java, webapp/src/main/java/info/rmapproject/webapp/controllers/EventDisplayController.java, webapp/src/main/java/info/rmapproject/webapp/controllers/ResourceDisplayController.java, webapp/src/main/java/info/rmapproject/webapp/controllers/SearchController.java, webapp/src/main/java/info/rmapproject/webapp/service/SearchServiceSolr.java, webapp/src/main/webapp/includes/stylesheets/layout.css, webapp/src/test/java/info/rmapproject/webapp/controllers/ResourceDisplayControllerTestIT.java, webapp/src/test/java/info/rmapproject/webapp/controllers/SearchControllerTestIT.java
Closes #230
When a Resource URI has special characters encoded into the querystring, they were being double decoded in RMap and this was causing matches not to be found for these URLs. The decoding already happens by default when the Path* annotations are used. This removes the additional http decoding which was causing problems when using the encoded parameter URLs.
It also replaces escaped quotes with regular quotes in results that are pulled from Solr when searching for labels.
=> Removed double HTTP decoding of parameters passed into API or GUI

webapp/src/main/java/info/rmapproject/webapp/controllers/HomeController.java, webapp/src/main/webapp/WEB-INF/tags/headerFull.tag, webapp/src/main/webapp/WEB-INF/views/about.jsp, webapp/src/main/webapp/WEB-INF/views/error.jsp, webapp/src/main/webapp/WEB-INF/views/home.jsp, webapp/src/main/webapp/WEB-INF/views/objectnotfound.jsp, webapp/src/main/webapp/WEB-INF/views/terms.jsp
- Added terms of use page. Needs additional work, but for now includes formal disclaimer, and notice about the public nature of the data and the absence of preservation during beta phase.
- Added information about IEEE data load to About page
- Added IEEE as a sample search on the home page, and changed doi example search to an IEEE doi that is in the initial data load
- Fixed a link to a non-existent search page on the error pages.
=> Final GUI text changes for release

core/src/main/java/info/rmapproject/core/rmapservice/impl/rdf4j/ORMapEventMgr.java, core/src/main/java/info/rmapproject/core/rmapservice/impl/rdf4j/ORMapObjectMgr.java, core/src/main/java/info/rmapproject/core/rmapservice/impl/rdf4j/ORMapResourceMgr.java, core/src/main/java/info/rmapproject/core/rmapservice/impl/rdf4j/triplestore/Rdf4jTriplestore.java
Closes issue #248
When a contextUri does not exist and it is used in rdf4j's triplestore.getStatements(sub,pred,obj,includeinf,context), it does not release the connection.  After the connections are used up, graphdb hangs. This is the same issue as in #123 and was replicated by repeatedly accessing a non existent URI on the /api/{discos|agent|event}/{uri} path.
I added code to check the contextUri is valid before calling getStatements() with the context param.
I manually tested on dev and can no longer replicate issue #248, but does need a series of integration tests - it's not clear at this point whether this is graphdb specific or related to the rdf4j library.
=> Changes to avoid unidentified contexts getting into getStatements

api/src/main/java/info/rmapproject/api/utils/PathUtils.java, webapp/src/main/webapp/WEB-INF/views/deleted.jsp
Fixes two minor things:
This was missed during the clean up in PR #240. Double decoding can destroy links that should contain encoded parts. The scope of what this affects is very narrow - it affects response header links in the API when you are paginating!
Test:
1. Perform a GET like this:
`curl -v "https://test.rmap-hub.org/api/resources/https%3A%2F%2Frosetest.library.jhu.edu%2Faor2-test%2F%23aor%2FRCPD1266%2Fbinding%2520front%2520cover%2Fimage?limit=1&page=1"`
2. View the response headers, there is a link that ends with `page=2`. Copy the resource part of the link `https://test.rmap-hub.org/api/resources/{resource}?limit=1&page=2`.
3. Paste the encoded resource part of the URL into a decoder e.g. https://meyerweb.com/eric/tools/dencoder/
4. If it is working correctly, when you decode, …
=> 2 minor fixes: Fix link on deleted page, remove extra http decode

api/src/main/java/info/rmapproject/api/auth/AuthenticationInterceptor.java
Wrong kind of equals used was causing OPTIONS and HEAD to require a key. Fortunately this seems to be the only symptom of the bad code. For some reason GET was fine without a key.
I have already tested this - it's fixed, and the code was clearly wrong before. 
If you wish to confirm, follow the instructions for running RMap locally:
https://github.com/rmap-project/rmap/blob/master/DEVELOPER.md#running-rmap
The following commands should return a link and allow header:
```
curl -i -X OPTIONS http://localhost:[portnum]/api/discos
curl -i -I HEAD http://localhost:[portnum]/api/discos
```
For the original behavior, see the live sites:
```
curl -i -X OPTIONS https://rmap-hub.org/api/discos
curl -i -I HEAD https://rmap-hub.org/api/discos
```
=> Fix string compare in authentication interceptor

DEVELOPER.md, README.md, api/src/main/java/info/rmapproject/api/responsemgr/AgentResponseManager.java, api/src/main/java/info/rmapproject/api/service/EventApiService.java, api/src/main/resources/rmapapi.properties, core/src/test/java/info/rmapproject/core/model/impl/rdf4j/ORMapDiscoTest.java, core/src/test/java/info/rmapproject/core/model/impl/rdf4j/ORMapEventCreationTest.java, core/src/test/java/info/rmapproject/core/model/impl/rdf4j/ORMapEventDeletionTest.java, core/src/test/java/info/rmapproject/core/model/impl/rdf4j/ORMapEventDerivationTest.java, core/src/test/java/info/rmapproject/core/rmapservice/impl/rdf4j/ORMapObjectMgrTest.java, core/src/test/java/info/rmapproject/core/rmapservice/impl/rdf4j/OStatementsAdapterTest.java, integration/src/test/java/info/rmapproject/integration/SmokeTestIT.java, webapp/src/main/webapp/WEB-INF/views/about.jsp, webapp/src/main/webapp/WEB-INF/views/user/login.jsp, webapp/src/main/webapp/WEB-INF/views/user/welcome.jsp
This change updates all references to the tech wiki URL to instead point to the new `rmap-documentation` project in GitHub (https://github.com/rmap-project/rmap-documentation)
Also includes 2 minor bug fixes on API that were discovered while testing example code against the API:
* `currPage` can be null, this fixes a NPE for currPage on `/agents/{uri}/discos` and `/agents/{uri}/events`.
* Incorrect parameter was causing incorrect JSON output on `/api/events/{uri}/discos` path.
I have put this and other changes in a combined .war deployment on test.rmap-hub.org. 
You can check the tech doc link points to the new location here:
https://test.rmap-hub.org/api/
and
https://test.rmap-hub.org/app/about#how-create-disco 
The `/agents/{uri}/discos` used to error, but now works: …
=> Update documentation links, 2 minor bug fixes

api/src/main/java/info/rmapproject/api/responsemgr/QueryParamHandler.java, api/src/main/java/info/rmapproject/api/utils/Constants.java, api/src/main/java/info/rmapproject/api/utils/HttpHeaderDateUtils.java, api/src/test/java/info/rmapproject/api/responsemgr/versioning/ResourceVersionsTest.java, api/src/test/java/info/rmapproject/api/responsemgr/versioning/TimegateTest.java, api/src/test/java/info/rmapproject/api/utils/HttpHeaderDateUtilsTestIT.java, core/src/test/java/info/rmapproject/core/rmapservice/impl/rdf4j/ORMapResourceMgrTest.java, core/src/test/java/info/rmapproject/core/rmapservice/impl/rdf4j/ORMapStatementMgrTest.java
Fixes 2 timezone issues:
1) When using the `Accept-Datetime`, the server was ignoring the timezone and assuming the timezone was whatever the server was set to. The utility now respects the timezone provided, and the string date is returned as GMT per Memento requirement. This issue is described in #46. I have re-enabled the corresponding tests.
2) Defines TimeZone as UTC on date filter queries in core - so when someone queries the API with a date it assumes that date is UTC every time. This keeps date filters consistent. Previously, it was applying date filter based on timezone of the server, so you would get different results depending on the region of timezone of the server.
Closes #46 
I have combined this and other PR changes in a new version available through test.rmap-hub.org. 
For …
=> Ensure timezone always set to UTC

core/src/main/java/info/rmapproject/core/model/impl/rdf4j/ORMapEvent.java
The `rmap:lineageProgenitor` was not being exposed through the `GET /rmap/events/{uri}` API. This adds it to the getModel() for Event.
I have loaded this combined with other changes to the test server. You can see the result here:
https://test.rmap-hub.org/api/events/ark%3A%2F99999%2Ffk4jq1bz77 
(`lineageProgenitor` is now present)
Previously, no lineageProgenitor:
https://rmap-hub.org/api/events/ark%3A%2F87281%2Ft2863gdf
=> Expose Event's rmap:lineageProgenitor through API
